import type { SupabaseClient } from "@supabase/supabase-js";

// Resolving the RADIUS server NETPID hands to an ISP's routers.
//
// WHY THIS EXISTS: the quick-add flow used to demand that each ISP type its own
// RADIUS address into provisioning defaults, and refused to add a router until
// they did. That is the platform's infrastructure leaking into the operator's
// UI — the ISP has no FreeRADIUS to point at, and asking for a server they
// cannot know is a question with no correct answer.
//
// The address is therefore resolved SERVER-SIDE, in this order, and the ISP
// never sees or types it:
//
//   1. the ISP's own override, if they genuinely run their own RADIUS
//      (isp_router_defaults.radius_server) — an escape hatch, not a step;
//   2. NETPID's platform RADIUS server — the row in radius_servers whose
//      isp_id IS NULL, which is what every ISP inherits by default;
//   3. the RADIUS_SERVER_HOST environment variable, as a deployment-level
//      fallback for a self-hosted install with no platform row.
//
// Every other source — the management IP, the API credentials, the NAS identity
// and shared secret — is already generated by NETPID in this same flow.

export type RadiusHost = { host: string; authPort: number; acctPort: number; source: string };

export async function resolveRadiusHost(
  svc: SupabaseClient,
  ispId: string,
  ispOverride?: string | null,
): Promise<RadiusHost | null> {
  // 1. An ISP that really does run its own RADIUS keeps it.
  const override = (ispOverride ?? "").trim();
  if (override) {
    return { host: override, authPort: 1812, acctPort: 1813, source: "isp" };
  }

  // 2. NETPID's platform RADIUS server. Order by isp_id nulls first so the
  //    platform row wins over any per-ISP row if one ever exists.
  const { data: servers } = await svc.from("radius_servers")
    .select("host, auth_port, acct_port, isp_id, status")
    .or(`isp_id.is.null,isp_id.eq.${ispId}`)
    .order("isp_id", { ascending: true, nullsFirst: true })
    .limit(1)
    .maybeSingle();

  const row = servers as { host: string; auth_port: number; acct_port: number; isp_id: string | null } | null;
  if (row?.host) {
    return {
      host: String(row.host),
      authPort: Number(row.auth_port ?? 1812),
      acctPort: Number(row.acct_port ?? 1813),
      source: row.isp_id ? "isp" : "platform",
    };
  }

  // 3. Deployment-level fallback.
  const envHost = (process.env.RADIUS_SERVER_HOST ?? "").trim();
  if (envHost) {
    return { host: envHost, authPort: 1812, acctPort: 1813, source: "env" };
  }

  return null;
}
